<?php

return [
    "rooms" => [
        [
            "name" => "Room View Sea",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Small Room",
            "rent" => "200 BDT",
            "rentDuration" => "Day",
            "size" => "25 sqft",
            "bed" => "King bed",
            "capacity" => "2",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Premium King Room",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Room Vip King",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Royal Room",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Room View Sea",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Small Room",
            "rent" => "200 BDT",
            "rentDuration" => "Day",
            "size" => "25 sqft",
            "bed" => "King bed",
            "capacity" => "2",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Premium King Room",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Room Vip King",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Royal Room",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Room View Sea",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Small Room",
            "rent" => "200 BDT",
            "rentDuration" => "Day",
            "size" => "25 sqft",
            "bed" => "King bed",
            "capacity" => "2",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Premium King Room",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Room Vip King",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Royal Room",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
    ]

];
