<?php

return [
    "rooms" => [
        [
            "name" => "Room View Sea",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Small Room",
            "rent" => "200 BDT",
            "rentDuration" => "Day",
            "size" => "25 sqft",
            "bed" => "King bed",
            "capacity" => "2",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Premium King Room",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Room Vip King",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Royal Room",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Room View Sea",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Small Room",
            "rent" => "200 BDT",
            "rentDuration" => "Day",
            "size" => "25 sqft",
            "bed" => "King bed",
            "capacity" => "2",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Premium King Room",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Room Vip King",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Royal Room",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Room View Sea",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Small Room",
            "rent" => "200 BDT",
            "rentDuration" => "Day",
            "size" => "25 sqft",
            "bed" => "King bed",
            "capacity" => "2",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Premium King Room",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Room Vip King",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
        [
            "name" => "Royal Room",
            "rent" => "400 BDT",
            "rentDuration" => "Day",
            "size" => "50 sqft",
            "bed" => "King beds",
            "capacity" => "5",
            "services" => "Wifi,Televisions,Fridge....",
        ],
    ],
    "news" => [
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],
        [
            "title" => "All hotels will be opened for 12 hours",
            "date" => "OCT 02, 2023",
            "type" => "Event",
            "description" => "A round-the-world trip remains the world’s greatest journey. For two out of every three people, this is the ultimate travel experience, according to recent research...",
        ],

    ],
    "roomTypes" => [
        [
            "title" => "Suit Rooms",
            "status" => "1",
            "description" => "Some content will place here"
        ],
        [
            "title" => "AC Rooms",
            "status" => "1",
            "description" => "Some content will place here"
        ],
        [
            "title" => "Non-ac Rooms",
            "status" => "1",
            "description" => "Some content will place here"
        ],
    ],

];
