@include('admin.layouts.partials.css')
@include('admin.layouts.partials.topbar')
@include('admin.layouts.partials.sidebar')
@yield('body')
@include('admin.layouts.partials.footer')
@include('admin.layouts.partials.js')
